{
  "hash": "00dc3592e1236c71f4f8aba7e82e85f5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 3\"\nauthor: \"Arya Siahaan\"\ndate: \"May 15, 2024\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n# VAST Challenge 2024\n\n### Mini-Challenge 2:\n\n#### Background\n\nIn Oceanus, the island's economy thrives on the movement of seafaring vessels, particularly those operated by commercial fishing companies, indicating a healthy economic state. However, a major event has disrupted these routines: SouthSeafood Express Corp was caught engaging in illegal fishing. This scandal caused significant turmoil within the close-knit fishing community. FishEye International, a non-profit dedicated to combating illegal fishing, seeks assistance to understand the impact of this event. They have been gathering and processing data on ship movements and shipping records to create CatchNet: the Oceanus Knowledge Graph. While analysts at FishEye ensure data accuracy, they require assistance to develop analytical capabilities for this data.\n\n#### Tasks and Questions:\n\nFishEye analysts require assistance in performing geographic and temporal analysis of the CatchNet data to prevent future instances of illegal fishing. The task involves developing innovative visual analytics tools and workflows designed to identify and understand signatures of various behaviors. One key objective is to visualize the signature of SouthSeafood Express Corp's illegal activities. Additionally, there is a need to create a workflow capable of detecting other instances of illegal behavior within the data. These efforts are crucial for enhancing FishEye's ability to monitor and combat illegal fishing effectively. This exercise will attempt to address Question 1 and Question 3 of this challenge.\n\n##### Question 1\n\nFishEye analysts have long wanted to better understand the flow of commercially caught fish through Oceanus’s many ports. But as they were loading data into CatchNet, they discovered they had purchased the wrong port records. They wanted to get the ship off-load records, but they instead got the port-exit records (essentially trucks/trains leaving the port area). Port exit records do not include which vessel that delivered the products. Given this limitation, develop a visualization system to associate vessels with their probable cargos. Which vessels deliver which products and when? What are the seasonal trends and anomalies in the port exit records?\n\n##### Question 3\n\nTo support further Fisheye investigations, develop visual analytics workflows that allow you to discover other vessels engaging in behaviors similar to SouthSeafood Express Corp’s illegal activities? Provide visual evidence of the similarities.\n\n## Getting Started\n\n### Loading the required R library packages\n\nFor the purpose of this exercise, several R packages will be used to perform the following tasks:\n\n-   Importing graph data in json file format into R\n\n-   Extracting the nodes and edges (also known as links) from imported graph data.\n\n-   Wrangling text data type.\n\n-   Importing geographical data in geojson file format into R,\n\n-   Importing geographical data in ESRI shapefile format into R,\n\n-   Extracting movement data from the edges table of a knowledge graph,\n\n-   Deriving a trajectory data from a movement data, and\n\n-   Visualising trajectory data to reveal geo-temporal patterns.\n\nThe following code chunk utilises the [`p_load()`](https://www.rdocumentation.org/packages/pacman/versions/0.5.1/topics/p_load) function from the [pacman](https://github.com/trinker/pacman) package to ensure that the necessary packages are available in the R environment. If the packages are already installed on the computer, [`p_load()`](https://www.rdocumentation.org/packages/pacman/versions/0.5.1/topics/p_load) will load them. If they are not installed, it will first install them and then load them into the R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, jsonlite, DataExplorer,\n               lubridate, ggplot2, tidygraph,\n               ggraph, igraph, sf, skimr) \n```\n:::\n\n\n### Loading The Data\n\nThe dataset for this exercise is available for download at the [Vast Challenge 2024](https://vast-challenge.github.io/2024/index.html). As I undertake Mini-Challenge 2, I will utilize the dataset provided in the form of a JSON file named `mc2.json`.\n\nIn the code chunk below, `fromJSON()` of **jsonlite** package is used to import `mc2.json` file into R and save the output object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_data <- fromJSON(\"data/mc2.json\")\n```\n:::\n\n\nThe output is called *`mc2_data`*. It is a large list R object.\n\n## DATA PREPARATION\n\n### Wrangling and tidying *edges* data.frame\n\n#### Extracting *edges* and removing duplicates\n\nThe code chunk below extracts the *links* data.frame from `mc2_data` and saves it as a tibble data.frame called `mc2_edges`. The `distinct()` function is used to remove duplicates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Wrangling and tidying edges\nmc2_edges <- as_tibble(mc2_data$links) %>% \n  distinct()\n```\n:::\n\n\nNext, `glimpse()` of **dplyr** package will be used to reveal the structure of `mc2_edges` tibble data table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mc2_edges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 271,643\nColumns: 17\n$ type                <chr> \"Event.TransportEvent.TransponderPing\", \"Event.Tra…\n$ time                <chr> \"2035-09-16T04:06:48.185987\", \"2035-09-20T05:21:33…\n$ dwell               <dbl> 115074.79, 412706.32, 286092.88, 327623.95, 243225…\n$ `_last_edited_by`   <chr> \"Olokun Daramola\", \"Melinda Manning\", \"Olokun Dara…\n$ `_date_added`       <chr> \"2035-09-16T00:59:46.300100\", \"2035-09-22T02:37:37…\n$ `_last_edited_date` <chr> \"2035-09-16T00:59:46.300100\", \"2035-09-22T02:37:37…\n$ `_raw_source`       <chr> \"Oceanus Vessel Locator System\", \"Oceanus Vessel L…\n$ `_algorithm`        <chr> \"OVLS-Catch&Hook\", \"OVLS-Catch&Hook\", \"OVLS-Catch&…\n$ source              <chr> \"City of Haacklee\", \"City of Haacklee\", \"City of H…\n$ target              <chr> \"perchplundererbc0\", \"perchplundererbc0\", \"perchpl…\n$ key                 <int> 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7,…\n$ date                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ data_author         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ aphorism            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ holiday_greeting    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ wisdom              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ `saying of the sea` <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nFrom the table above, the following data issues can be identified:\n\n-   Columns with date and time data type are not in the correct format.\n\n-   The column `type` also seems to contain three different types of information, namely: 'Event', 'TransportEvent', 'TransponderPing'.\n:::\n\n#### **Correcting time and date data type from mc2_edges data.frame**\n\nIn the code chunk below, `as_datetime()` of **lubridate** package is used to convert fields with character date into **POSIXt** format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_edges$time <- as_datetime(mc2_edges$time)\nmc2_edges$\"date\" <- as_datetime(\"mc2_edges$date\")\n```\n:::\n\n\nNext, `glimpse()` will be used again to confirm if the process have been performed correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mc2_edges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 271,643\nColumns: 17\n$ type                <chr> \"Event.TransportEvent.TransponderPing\", \"Event.Tra…\n$ time                <dttm> 2035-09-16 04:06:48, 2035-09-20 05:21:33, 2035-09…\n$ dwell               <dbl> 115074.79, 412706.32, 286092.88, 327623.95, 243225…\n$ `_last_edited_by`   <chr> \"Olokun Daramola\", \"Melinda Manning\", \"Olokun Dara…\n$ `_date_added`       <chr> \"2035-09-16T00:59:46.300100\", \"2035-09-22T02:37:37…\n$ `_last_edited_date` <chr> \"2035-09-16T00:59:46.300100\", \"2035-09-22T02:37:37…\n$ `_raw_source`       <chr> \"Oceanus Vessel Locator System\", \"Oceanus Vessel L…\n$ `_algorithm`        <chr> \"OVLS-Catch&Hook\", \"OVLS-Catch&Hook\", \"OVLS-Catch&…\n$ source              <chr> \"City of Haacklee\", \"City of Haacklee\", \"City of H…\n$ target              <chr> \"perchplundererbc0\", \"perchplundererbc0\", \"perchpl…\n$ key                 <int> 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7,…\n$ date                <dttm> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ data_author         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ aphorism            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ holiday_greeting    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ wisdom              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ `saying of the sea` <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nAs we can see now, the `time` and `date` columns have been converted to **datetime** format.\n:::\n\n#### **Splitting words**\n\n![](images/clipboard-3479349286.png)\n\nFrom the table above, we can see that the text in the `type` column is not tidy. I will tidy the `type` column by splitting it into three new separate columns called `event1`, `event2`, and `event3`. However, I will only keep the columns containing the values 'TransportEvent' and 'TransponderPing', which will be `event2` and `event3`.\n\n#### Splitting and Tidying the 'type' Column from mc2_edges data.frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\nword_list <- strsplit(mc2_edges$type, \"\\\\.\")\n\n# The code chunk below will be used to find the maximum number of elements in any split\nmax_elements <- max(lengths(word_list)) #to find the maximum number of elements in any split\n\n#The code chunk below will be used to pad shorter splits with NA values to make them all the same length.\nword_list_padded <- lapply(word_list, \nfunction(x) c(x, rep(NA, max_elements - length(x)))) #to pad shorter splits with NA values to make them all the same length.\nword_df <- do.call(rbind, word_list_padded)\ncolnames(word_df) <- paste0(\"event\", 1:max_elements)\n\n# Since the output above is a matrix, the code chunk below is used to convert word_df into a tibble data.frame.\nword_df <- as_tibble(word_df) %>%\n  select(event2, event3)\n\n\n# The code chunk below appends the extracted columns back to mc2_edges tibble data.frame\nmc2_edges <- mc2_edges %>%\n  cbind(word_df)\n```\n:::\n\n\nThis code splits the `type` column into multiple components, pads shorter entries with NAs, and integrates them back into the `mc2_edges` data.frame as new columns.\n\n![](images/clipboard-2806146328.png)\n\n::: {.callout-tip title=\"Observation\"}\nAs we can see here, two new columns, `event2` and `event3`, have been created and appended to the `mc2_edges` data.frame.\n:::\n\n### Initial EDA of mc2_edges data.frame\n\nAfter cleaning and preparing the `mc2_edges` data.frame, I want to understand how the newly formed structure looks. Let's make use of the **DataExplorer** package to visualize it.\n\nThe code below uses the `plot_intro` function, which is part of the **DataExplorer** package. This function provides a high-level summary of the `mc2_edges` data.frame, offering insights into its structure and content.\n\n::: panel-tabset\n## The plot\n\n![](images/clipboard-2055116904.png)\n\n![](images/clipboard-1180112888.png)\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot introduction of the data\nplot_intro(mc2_edges, title = \"Introduction of mc2_edges Data\")\n```\n:::\n\n:::\n\nThe `plot_str` function below generates a plot that visualizes the structure of `mc2_edges` data.frame, showing the relationships between different columns and their types.\n\n::: panel-tabset\n## The plot\n\n![](images/clipboard-2619173514.png)\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate and display the data structure plot\nplot_str(mc2_edges)\n```\n:::\n\n:::\n\nThe `plot_missing` function below generates a visualization that helps to identify and understand the distribution of missing values within `mc2_edges` data.frame.\n\n::: panel-tabset\n## The plot\n\n![](images/clipboard-299140884.png)\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot missing values\nplot_missing(mc2_edges, title = \"Missing Values in mc2_edges Data\")\n```\n:::\n\n:::\n\n### Further cleaning of mc2_edges data.frame\n\nAfter the initial EDA, I will remove columns from `mc2_edges` data.frame that are unnecessary to complete Mini-Challenge 2.\n\n#### Dropping unnecessary columns from mc2_edges data.frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_edges_cleaned <- mc2_edges %>%\n  select(-c(`type`, `_last_edited_by`, `_date_added`, `_last_edited_date`, `_raw_source`, `_algorithm`, `key`,  `data_author`, `aphorism`, `holiday_greeting`, `wisdom`, `saying of the sea`))\n```\n:::\n\n\nThe code above removes unnecessary columns from `mc2_edges` that are not needed for analysis, and then assigns the cleaned-up version to a new data.frame called `mc2_edges_cleaned`.\n\nNext, let's use `glimpse()` to check what `mc2_edges_cleaned` looks like.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mc2_edges_cleaned)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 271,643\nColumns: 7\n$ time   <dttm> 2035-09-16 04:06:48, 2035-09-20 05:21:33, 2035-09-28 04:31:47,…\n$ dwell  <dbl> 115074.79, 412706.32, 286092.88, 327623.95, 243225.35, 109564.2…\n$ source <chr> \"City of Haacklee\", \"City of Haacklee\", \"City of Haacklee\", \"Ci…\n$ target <chr> \"perchplundererbc0\", \"perchplundererbc0\", \"perchplundererbc0\", …\n$ date   <dttm> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ event2 <chr> \"TransportEvent\", \"TransportEvent\", \"TransportEvent\", \"Transpor…\n$ event3 <chr> \"TransponderPing\", \"TransponderPing\", \"TransponderPing\", \"Trans…\n```\n\n\n:::\n:::\n\n\nBefore moving to the next task, it would be wise to save the tidied `mc2_edges_cleaned` data.frame into a physical file for future use. By doing so, repeating the steps above will not be necessary.\n\nThe code chunk below will be used to save `mc2_edges_cleaned` into R **rds** file format.\n\n::: callout-warning\nSince the file will be saved in the `rds` sub-folder within the `data` folder, ensure that the `rds` folder exists. If it does not, it needs to be created first.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mc2_edges_cleaned, \"data/rds/mc2_edges_cleaned.rds\")\n```\n:::\n\n\nThis completes the data preparation process for the *links* data.frame of `mc2_data`, which is now stored in the `mc2_edges_cleaned` data.frame and saved as a physical `mc2_edges_cleaned.rds` file.\n\nThe next step is to clean and prepare the *nodes* data.frame of `mc2_data`.\n\n### Wrangling and tidying *nodes* data.frame\n\n#### Extracting *nodes* and removing duplicates\n\nThe code chunk below extracts the *nodes* data.frame from `mc2_data`, parses it as a tibble data.frame called `mc2_nodes`, and removes duplicate rows using the `distinct()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_nodes <- as_tibble(mc2_data$nodes) %>%\n  distinct()\n```\n:::\n\n\nNext, the code chunk below uses the `glimpse()` function to reveal the data structure of the `mc2_nodes` tibble data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mc2_nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,637\nColumns: 20\n$ type                 <chr> \"Entity.Commodity.Fish\", \"Entity.Commodity.Fish\",…\n$ `_last_edited_by`    <chr> \"Clepper Jessen\", \"Clepper Jessen\", \"Haenyeo Hyun…\n$ `_date_added`        <chr> \"2033-09-04T00:00:00\", \"2034-01-21T00:00:00\", \"20…\n$ `_last_edited_date`  <chr> \"2035-01-25T00:00:00\", \"2035-01-04T00:00:00\", \"20…\n$ `_raw_source`        <chr> \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"Oceanus:…\n$ `_algorithm`         <chr> \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"…\n$ name                 <chr> \"Cod/Gadus n.specificatae\", \"Birdseye/Pisces frig…\n$ id                   <chr> \"gadusnspecificatae4ba\", \"piscesfrigus900\", \"pisc…\n$ Name                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"Haacklee…\n$ Description          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Activities           <list> <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, …\n$ kind                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"city\", \"…\n$ qty_tons             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ date                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ flag_country         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ company              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ tonnage              <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ length_overall       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ style                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ fish_species_present <list> <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, …\n```\n\n\n:::\n:::\n\n\n::: callout-note\nFrom the table above, the following data issues can be identified:\n\n-   The column `date` data type is not in the correct format.\n\n-   The values in Activities and fish_species_present fields are in **list** data type, which will affect the ability to process and to analyse the data.\n\n-   As shown in the screenshot below, some values in the Activities field are not ready to be analyse without further tidying (i.e. removing c(““)).\n:::\n\n#### **Correcting date data type from mc2_nodes data.frame**\n\nIn the code chunk below, `as_datetime()` of **lubridate** package is used to convert date fields with character date into **POSIXt** format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_nodes$date <- as_datetime(mc2_nodes$date)\n```\n:::\n\n\nNext, `glimpse()` will be used again to confirm if the process have been performed correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mc2_nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,637\nColumns: 20\n$ type                 <chr> \"Entity.Commodity.Fish\", \"Entity.Commodity.Fish\",…\n$ `_last_edited_by`    <chr> \"Clepper Jessen\", \"Clepper Jessen\", \"Haenyeo Hyun…\n$ `_date_added`        <chr> \"2033-09-04T00:00:00\", \"2034-01-21T00:00:00\", \"20…\n$ `_last_edited_date`  <chr> \"2035-01-25T00:00:00\", \"2035-01-04T00:00:00\", \"20…\n$ `_raw_source`        <chr> \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"Oceanus:…\n$ `_algorithm`         <chr> \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"…\n$ name                 <chr> \"Cod/Gadus n.specificatae\", \"Birdseye/Pisces frig…\n$ id                   <chr> \"gadusnspecificatae4ba\", \"piscesfrigus900\", \"pisc…\n$ Name                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"Haacklee…\n$ Description          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Activities           <list> <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, …\n$ kind                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"city\", \"…\n$ qty_tons             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ date                 <dttm> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ flag_country         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ company              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ tonnage              <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ length_overall       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ style                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ fish_species_present <list> <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, …\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nAs we can see now, the time and date columns have been converted to datetime format.\n:::\n\nThere are two more additional data issues can be observed. They are:\n\nThe values in `Activities` and `fish_species_present` columns are in list data type, which will affect the ability to process and to analyze the data.\n\nAs shown in the screenshot below, some values in the `Activities` and `fish_species_present`column are not ready to be analyze without further tidying (i.e. removing c(““)).\n\n![](images/clipboard-2425530968.png)\n\n#### Tidying Text Field\n\nIn the code chunk below, `mutate()` from `dplyr` and `gsub()` from Base R are used to perform the data tidying task.\n\nThis cleans up the `Activities` and `fish_species_present` columns by removing unnecessary characters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_nodes <- mc2_nodes %>%\n  mutate(Activities = gsub(\"c[(]\", \"\", Activities)) %>% \n  mutate(Activities = gsub(\"\\\"\", \"\", Activities)) %>%\n  mutate(Activities = gsub(\"[)]\", \"\", Activities)) \n\nmc2_nodes <- mc2_nodes %>%\n  mutate(fish_species_present = gsub(\"c[(]\", \"\", fish_species_present)) %>% \n  mutate(fish_species_present = gsub(\"\\\"\", \"\", fish_species_present)) %>%\n  mutate(fish_species_present = gsub(\"[)]\", \"\", fish_species_present)) \n```\n:::\n\n\nAfter executing the code chunk above, we can see from the screenshot below, that the text field in `Activities` and `fish_species_present` columns have been tidied.\n\n![](images/clipboard-3517877848.png)\n\n### **Initial EDA of mc2_nodes data.frame**\n\nNow, let's use the DataExplorer package again to visualize the `mc2_nodes` data.frame in a similar manner as was done above for the `mc2_edges` data.frame.\n\n::: panel-tabset\n## The plot\n\n![](images/clipboard-4088556349.png)\n\n![](images/clipboard-290209426.png)\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot introduction of the data\nplot_intro(mc2_nodes, title = \"Introduction of mc2_nodes Data\")\n```\n:::\n\n:::\n\nThe `plot_str` function below generates a plot that visualizes the structure of `mc2_nodes` data.frame, showing the relationships between different columns and their types.\n\n::: panel-tabset\n## The plot\n\n![](images/clipboard-1740825281.png)\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate and display the data structure plot\nplot_str(mc2_nodes)\n```\n:::\n\n:::\n\nThe `plot_missing` function below generates a visualization that helps to identify and understand the distribution of missing values within `mc2_nodes` data.frame.\n\n::: panel-tabset\n## The plot\n\n![](images/clipboard-1008176763.png)\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot missing values\nplot_missing(mc2_nodes, title = \"Missing Values in mc2_nodes Data\")\n```\n:::\n\n:::\n\n### **Further Cleaning of mc2_nodes data.frame**\n\nAfter the initial EDA, I will remove columns from `mc2_nodes` data.frame that are unnecessary to complete Mini-Challenge 2.\n\n#### Dropping unnecessary Columns from mc2_nodes data.frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_nodes_cleaned <- mc2_nodes %>%\n  select(-c(`_last_edited_by`, `_date_added`, `_last_edited_date`, `_raw_source`, `_algorithm`, `style`))\n```\n:::\n\n\nThe code above removes unnecessary columns from `mc2_nodes` that are not needed for analysis, and then assigns the cleaned-up version to a new data.frame called `mc2_nodes_cleaned`.\n\nNext, let’s use `glimpse()` to check what `mc2_nodes_cleaned` looks like.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mc2_nodes_cleaned)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,637\nColumns: 14\n$ type                 <chr> \"Entity.Commodity.Fish\", \"Entity.Commodity.Fish\",…\n$ name                 <chr> \"Cod/Gadus n.specificatae\", \"Birdseye/Pisces frig…\n$ id                   <chr> \"gadusnspecificatae4ba\", \"piscesfrigus900\", \"pisc…\n$ Name                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"Haacklee…\n$ Description          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Activities           <chr> \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"…\n$ kind                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"city\", \"…\n$ qty_tons             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ date                 <dttm> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ flag_country         <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ company              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ tonnage              <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ length_overall       <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ fish_species_present <chr> \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"…\n```\n\n\n:::\n:::\n\n\nThe tidied mc2_nodes_cleaned data.frame will then be saved into a physical file for future use. By doing so, repeating the steps above will not be necessary.\n\nThe code chunk below will be used to save mc2_nodes_cleaned into R rds file format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mc2_nodes_cleaned, \"data/rds/mc2_nodes_cleaned.rds\")\n```\n:::\n\n\nThis completes the data preparation process for the *nodes* data.frame of `mc2_data`, which is now stored in the `mc2_nodes_cleaned` data.frame and saved as a physical `mc2_nodes_cleaned.rds` file.\n\n### Importing Geographical Data in GEOJSON format\n\nNext I need to import geographical data. The data is in the form of GEOJSON file. GEOJSON is an open standard format designed for representing simple geographical features, along with their non-spatial attributes. It is based on the JSON format. I will import this using the `sf` package.\n\nIn the code chunk below, `st_read()` of **sf** package is used to import a geographical file in [geojson](https://en.wikipedia.org/wiki/GeoJSON) format into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noceanusgeography = st_read(\"data/OceanusGeography.geojson\") %>%\n  st_transform(crs = 4326)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OceanusGeography' from data source \n  `C:\\aryasiahaan\\ISSS608-VAA\\Take-home_Ex\\Take-home_Ex03\\data\\OceanusGeography.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 29 features and 7 fields\nGeometry type: GEOMETRY\nDimension:     XY\nBounding box:  xmin: -167.0654 ymin: 38.07452 xmax: -163.2723 ymax: 40.67775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Thing to learn from the code chunk above\"}\n`st_transform()` is used to assign wgs84 (i.e. 4326) coordinates system to the output object.\n:::\n\nThe output R object (i.e. oceanusgeography) is an sf data.frame as shown below. Actually sf stand for simple feature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(oceanusgeography)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sf\"         \"data.frame\"\n```\n\n\n:::\n:::\n\n\nNext, `glimpse()` is used to display the structure of *oceanusgeography* sf data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(oceanusgeography)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 29\nColumns: 8\n$ Name                 <chr> \"Suna Island\", \"Thalassa Retreat\", \"Makara Shoal\"…\n$ Description          <chr> \"Large island of Oceanus\", \"Smaller island of Oce…\n$ X.note               <chr> \"Suna is 'sand' or 'gritty' in Japanese\", \"Thalas…\n$ type                 <chr> \"Entity.Location.Region\", \"Entity.Location.Region…\n$ X.Kind               <chr> \"Island\", \"Island\", \"Island\", \"Island\", \"Fishing …\n$ Activities           <list> \"Residential\", \"Residential\", \"Recreation\", <\"To…\n$ fish_species_present <list> <>, <>, <>, <>, <\"Cod/Gadus n.specificatae\", \"Bi…\n$ geometry             <GEOMETRY [°]> MULTIPOLYGON (((-166.0111 3..., MULTIPOL…\n```\n\n\n:::\n:::\n\n\n::: callout-note\nThe geometry column indicate the simple feature geometry is multipolygon. However, if the data.frame is examined closely, we can see that the geographical data are captured in polygon and point features.\n:::\n\n#### Visualising Geographical Data with ggplot2\n\nIt is always a good practice to visualize the sf data.frame in a map.\n\nIn the code chunk below, geom_sf() of ggplot2 package is used to plot the sf data.frame in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = oceanusgeography) +\n  geom_sf()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nBefore moving on to next section, let’s save oceanusgeography into rds format for future use by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(oceanusgeography, \"data/rds/oceanusgeography.rds\")\n```\n:::\n\n\nThis completes the data preparation process for the *`oceanusgeography`* data.frame, which is now stored in the `oceanusgeography` data.frame and saved as a physical `oceanusgeography.rds` file.\n\n#### Importing Geographical Data in ESRI shapefile format\n\nIn the code chunk below, `st_read()` of **sf** package is used to import a geographical file in [ESRI shapefile](#0) format into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noceanuslocations <- st_read(dsn = \"data/shp\",\n  layer = \"Oceanus Geography\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Oceanus Geography' from data source \n  `C:\\aryasiahaan\\ISSS608-VAA\\Take-home_Ex\\Take-home_Ex03\\data\\shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 27 features and 7 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -167.0654 ymin: 38.07452 xmax: -163.2723 ymax: 40.67775\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nNext `class()` is used verify if the *`oceanuslocations`* is indeed in sf data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(oceanuslocations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sf\"         \"data.frame\"\n```\n\n\n:::\n:::\n\n\nSimilarly, `glimpse()` is used to reveal the structure of *`oceanuslocation`*s data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(oceanuslocations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 27\nColumns: 8\n$ Name       <chr> \"Haacklee\", \"Port Grove\", \"Lomark\", \"Himark\", \"Paackland\", …\n$ Descriptio <chr> NA, NA, NA, NA, NA, \"Adimistrative seat of Oceanus\", NA, NA…\n$ X.note     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ Activities <chr> \"Tourism,Local shipping\", \"Tourism,Research\", \"Deep sea fis…\n$ type       <chr> \"Entity.Location.City\", \"Entity.Location.City\", \"Entity.Loc…\n$ X.Kind     <chr> \"city\", \"city\", \"city\", \"city\", \"city\", \"city\", \"city\", \"bu…\n$ fish_speci <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ geometry   <POINT [°]> POINT (-165.6908 39.03215), POINT (-165.8855 39.10005…\n```\n\n\n:::\n:::\n\n\nLet's visualize the geographical data by using `geom_sf()` of ggplot2 as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = oceanuslocations) +\n  geom_sf()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nBefore moving on to the next section, the code chunk below is used to save *oceanuslocations* into an rds file format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(oceanuslocations, \n  \"data/rds/oceanuslocations.rds\")\n```\n:::\n\n\nThis completes the data preparation process for the *oceanuslocations*, which is now stored in the `oceanuslocations` data.frame and saved as a physical `oceanuslocations.rds` file.\n\n## DATA ANALYSIS\n\nAfter completing the data preparation process, the next step is to perform the analysis required to complete Mini-Challenge 2. From the background information above, we know that \"SouthSeafood Express Corp\" has been caught fishing illegally. Now, let's see what we can discover from the available data regarding their illegal behavior.\n\n### Importing Edges Data\n\nNow it is time to bring mc2_edges_cleaned.rds into R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc2_edges_cleaned <- read_rds(\"data/rds/mc2_edges_cleaned.rds\")\n```\n:::\n\n\nNext, `unique()` is used to list the unique classes in *event3* column of *mc2_edges* data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(mc2_edges_cleaned$event3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"TransponderPing\" NA               \n```\n\n\n:::\n:::\n\n\nThe output above shows that there are two unique classes in the event3. They are: *TransponderPing* and NA.\n\n### Extract Vessel Movement Data\n\nThe code chunk below is used to extract vessel movement data based on TransponderPing from mc2_edges.\n\n::: {.callout-tip title=\"Thing to learn from the code chunk above\"}\n-   `filter()` is used to select records with event3 is TransponderPing, and\n\n-   `select()` is used to fields that are needed to be saved\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvessel_movement_data <- mc2_edges_cleaned %>%\n  filter(event3 == \"TransponderPing\") %>%\n  select(time, dwell, source, target)\n```\n:::\n\n\nNext, unique() is used to list unique classes in source field.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(vessel_movement_data$source)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"City of Haacklee\"        \"City of Lomark\"         \n [3] \"City of Himark\"          \"City of Paackland\"      \n [5] \"City of South Paackland\" \"City of Port Grove\"     \n [7] \"Exit West\"               \"Nav 3\"                  \n [9] \"Nav D\"                   \"Nav B\"                  \n[11] \"Nav A\"                   \"Nav C\"                  \n[13] \"Nav 2\"                   \"Nav 1\"                  \n[15] \"Exit East\"               \"Exit South\"             \n[17] \"Exit North\"              \"Nav E\"                  \n[19] \"Cod Table\"               \"Ghoti Preserve\"         \n[21] \"Wrasse Beds\"             \"Nemo Reef\"              \n[23] \"Don Limpet Preserve\"     \"Tuna Shelf\"             \n```\n\n\n:::\n:::\n\n\nas well as oceanuslocation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(oceanuslocations$Name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Haacklee\"            \"Port Grove\"          \"Lomark\"             \n [4] \"Himark\"              \"Paackland\"           \"Centralia\"          \n [7] \"South Paackland\"     \"Exit West\"           \"Nav 3\"              \n[10] \"Nav D\"               \"Nav B\"               \"Nav A\"              \n[13] \"Nav C\"               \"Nav 2\"               \"Nav 1\"              \n[16] \"Exit East\"           \"Exit South\"          \"Exit North\"         \n[19] \"Nav E\"               \"Don Limpet Preserve\" \"Tuna Shelf\"         \n[22] \"Makara Shoal\"        \"Silent Sanctuary\"    \"Cod Table\"          \n[25] \"Ghoti Preserve\"      \"Wrasse Beds\"         \"Nemo Reef\"          \n```\n\n\n:::\n:::\n\n\n::: callout-note\nBecause later we are going to append the coordinates values from `oceanuslocations` to `vessel_movement_data`, it is very important for to ensure that the class values in `source` column of `vessel_movement_data` is similar to `Name` column of `oceanuslocations`.\n:::\n\nIn the code chunk below, gsub() is used to remove \"City of\" from source column. At the same time, `gsub()` is used to exclude the extra white space in from of the words.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvessel_movement_data <- vessel_movement_data%>%\n  mutate(source = gsub(\"^City of\", \"\", source)) %>%\n  mutate(source = gsub(\"^\\\\s+\", \"\", source))\n```\n:::\n\n\nNotice that the words \"City of\" have been remove from all records in `source` column from `vessel_movement_data` data.frame as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(vessel_movement_data$source)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Haacklee\"            \"Lomark\"              \"Himark\"             \n [4] \"Paackland\"           \"South Paackland\"     \"Port Grove\"         \n [7] \"Exit West\"           \"Nav 3\"               \"Nav D\"              \n[10] \"Nav B\"               \"Nav A\"               \"Nav C\"              \n[13] \"Nav 2\"               \"Nav 1\"               \"Exit East\"          \n[16] \"Exit South\"          \"Exit North\"          \"Nav E\"              \n[19] \"Cod Table\"           \"Ghoti Preserve\"      \"Wrasse Beds\"        \n[22] \"Nemo Reef\"           \"Don Limpet Preserve\" \"Tuna Shelf\"         \n```\n\n\n:::\n:::\n\n\n### **Further Data Wrangling**\n\nIn the code chunk below, `st_coordinate()` of **sf** package is used to extract coordinates from `oceanuslocations` sf data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(oceanuslocations)\n```\n:::\n\n\nNext, code chunk below is used to drop the *`geometry`* column of *`oceanuslocations`* sf data.frame by using `st_drop_geometry()` of **`sf`** package and save the output into a new data.frame called *`oceanuslocations_df`*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noceanuslocations_df <- oceanuslocations %>%\n  st_drop_geometry()\n```\n:::\n\n\nThen, the code chunk below is to append the x- and y-coodinate values from coords list into the `XCOORD` and `YCOORD` columns of `oceanuslocations_df` respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noceanuslocations_df$XCOORD <- coords[, \"X\"]\noceanuslocations_df$YCOORD <- coords[, \"Y\"]\n```\n:::\n\n\nIn the code chunk below, `class()` is used to confirm that the output is indeed a data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(oceanuslocations_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data.frame\"\n```\n\n\n:::\n:::\n\n\nLastly, the code chunk below is used to tidy `oceanuslocations_df` by selecting the necessary columns only and at the same time, rename `X.Kind` to `loc_type`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noceanuslocations_df <- oceanuslocations_df %>%\n  select(Name, type, X.Kind, XCOORD, YCOORD) %>%\n  rename(loc_type = X.Kind)\n```\n:::\n\n\nIn the code chunk below, `left_join()` of `dplyr` package is used to append columns in `oceanuslocations_df` data.frame to `vessel_movement_data` data.frame by matching the `source` column `vessel_movement_data` data.frame and the `Name` column from `oceanuslocations_df` data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvessel_movement_data <- vessel_movement_data %>%\n  left_join(oceanuslocations_df,\n            by = c(\"source\" = \"Name\"))\n```\n:::\n\n\nNext, this newly updated `vessel_movement_data` data.frame will be saved to a physical `vessel_movement_data.rds` file\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(vessel_movement_data, \"data/rds/vessel_movement_data.rds\")\n```\n:::\n\n\n### Creating Vessel Trajectory Data\n\nNow it is time to convert the *vessel movement data* into *vessel trajectory data*. A trajectory is a sequence of observations in time and space, for examples, the path formed by fishing vessels.\n\nIn the code chunk below, `st_as_sf()` of **sf** package is used to convert *`vessel_movement_data`* data.frame into `sf` point data.frame by using values in `XCOORD` and `YCOORD` columns. The output is an `sf` data.frame called *`vessel_movement_sf`*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvessel_movement_sf <- vessel_movement_data %>%\n  st_as_sf(coords = c(\"XCOORD\", \"YCOORD\"), \n           crs = 4326)\n```\n:::\n\n\nNext `arrange()` is used to sort the records according to the vessels’ name (i.e. target) and navigation time (i.e. time)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvessel_movement_sf <- vessel_movement_sf %>%\n  arrange(target, time)\n```\n:::\n\n\nLastly, `st_cast()` of **sf** package is used to convert *vessel_movement_sf* from point features into linestring features called *vessel_trajectory*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvessel_trajectory <- vessel_movement_sf %>%\n  group_by(target) %>%\n  summarize(do_union = FALSE) %>%\n  st_cast(\"LINESTRING\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(vessel_trajectory)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 296\nColumns: 2\n$ target   <chr> \"albacoreangler47d\", \"albacoreassaulter482\", \"amberjackassaul…\n$ geometry <LINESTRING [°]> LINESTRING (-164.5496 39.11..., LINESTRING (-164.3…\n```\n\n\n:::\n:::\n\n\nNow that I have the required vessel trajectory data, I need to find out which vessels belong to \"SouthSeafood Express Corp\".\n\n## Let's begin the investigation!\n\n#### Investigate 'type' column from the nodes data\n\nNext, I will use the `unique()` function from the base R package to see all the distinct entries in the `type` column of the `mc2_nodes_cleaned` data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(mc2_nodes_cleaned$type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Entity.Commodity.Fish\"          \"Entity.Location.City\"          \n [3] \"Entity.Document.DeliveryReport\" \"Entity.Vessel.FishingVessel\"   \n [5] \"Entity.Vessel.Other\"            \"Entity.Vessel.Ferry.Passenger\" \n [7] \"Entity.Vessel.CargoVessel\"      \"Entity.Vessel.Ferry.Cargo\"     \n [9] \"Entity.Vessel.Research\"         \"Entity.Vessel.Tour\"            \n[11] \"Entity.Location.Point\"          \"Entity.Location.Region\"        \n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nThe `type` column from the nodes data seems to contain a mix of information. Some of the entries appear interesting and useful for analysis, including:\n\n-   Entity.Commodity.Fish\n\n-   Entity.Document.DeliveryReport\n\n-   Entity.Location.City\n\n-   Entity.Location.Point\n\n-   Entity.Location.Region\n\n-   Entity.Vessel.CargoVessel\n\n-   Entity.Vessel.FishingVessel\n\nThe other entries seem useless.\n:::\n\nNext, I will try to find out the count of each entry. The code chunk below allows me to see the count of unique value in each entry.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_type_counts <- mc2_nodes_cleaned %>%\n  group_by(type) %>%\n  summarise(count = n())\n\n# Display the result\nprint(nodes_type_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   type                           count\n   <chr>                          <int>\n 1 Entity.Commodity.Fish             10\n 2 Entity.Document.DeliveryReport  5307\n 3 Entity.Location.City               6\n 4 Entity.Location.Point             12\n 5 Entity.Location.Region             6\n 6 Entity.Vessel.CargoVessel        100\n 7 Entity.Vessel.Ferry.Cargo          2\n 8 Entity.Vessel.Ferry.Passenger      3\n 9 Entity.Vessel.FishingVessel      178\n10 Entity.Vessel.Other                5\n11 Entity.Vessel.Research             2\n12 Entity.Vessel.Tour                 6\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nBased on the table above, we can see that there are:\n\n-   10 Fish Types.\n\n-   5307 Delivery Reports.\n\n-   6 City Names\n\n-   12 Point Locations\n\n-   6 Region Locations\n\n-   100 Cargo Vessels.\n\n-   178 Fishing Vessels.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter fishing vessels and rename specific columns while keeping all others\nfishing_vessel <- mc2_nodes_cleaned %>%\n  filter(type %in% c(\"Entity.Vessel.FishingVessel\")) %>%\n  rename(\n    fishing_vessel_id = id,\n    fishing_vessel_name = Name\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(fishing_vessel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 178\nColumns: 14\n$ type                 <chr> \"Entity.Vessel.FishingVessel\", \"Entity.Vessel.Fis…\n$ name                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ fishing_vessel_id    <chr> \"wavewranglerc2d\", \"yellowfintunataker08b\", \"arct…\n$ fishing_vessel_name  <chr> \"Wave Wrangler\", \"Yellowfin Tuna Taker\", \"Arctic …\n$ Description          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ Activities           <chr> \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"…\n$ kind                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ qty_tons             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ date                 <dttm> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ flag_country         <chr> \"Oceanus\", \"Oceanus\", \"Oceanus\", \"Oceanus\", \"Ocea…\n$ company              <chr> \"Roth, Logan and Moreno\", \"Brown-Haas\", \"Smith, D…\n$ tonnage              <int> 700, 4500, 1500, 400, 300, 7400, 100, 6500, 600, …\n$ length_overall       <int> 110, 110, 80, 60, 50, 130, 10, 90, 70, 120, 110, …\n$ fish_species_present <chr> \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"NULL\", \"…\n```\n\n\n:::\n:::\n\n\nAfter creating a new data.frame called `fishing_vessel` to isolate fishing vessel information, I want to find out which of these fishing vessels are registered under \"SouthSeafood Express Corp\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter fishing vessels registered under \"SouthSeafood Express Corp\"\nsouthseafood_fishing_vessels <- fishing_vessel %>%\n  filter(company == \"SouthSeafood Express Corp\")\n\n# Display the result\nprint(southseafood_fishing_vessels)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 14\n  type  name  fishing_vessel_id fishing_vessel_name Description Activities kind \n  <chr> <chr> <chr>             <chr>               <chr>       <chr>      <chr>\n1 Enti… <NA>  snappersnatcher7… Snapper Snatcher    <NA>        NULL       <NA> \n2 Enti… <NA>  roachrobberdb6    Roach Robber        <NA>        NULL       <NA> \n# ℹ 7 more variables: qty_tons <dbl>, date <dttm>, flag_country <chr>,\n#   company <chr>, tonnage <int>, length_overall <int>,\n#   fish_species_present <chr>\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nThe fishing vessels belonging to \"SouthSeafood Express Corp\" are:\n\n-   Snapper Snatcher (`snappersnatcher7be`)\n\n-   Roach Robber (`roachrobberdb6`)\n:::\n\n### Visualising the Geo-Temporal Patterns of the Vessels\n\nAfter identifying the vessels belonging to \"SouthSeafood Express Corp,\" I will visualize the geo-temporal patterns of the vessels \"Snapper Snatcher\" and \"Roach Robber.\"\n\nLet's start with \"Snapper Snatcher.\" The code chunk below selects and isolates the appropriate data records belonging to \"Snapper Snatcher\" using their vessel ID, `snappersnatcher7be`, located within the target column in the `vessel_trajectory` data.frame. The result will be stored in a new data.frame called `snapsnatch_trajectory`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnapsnatch_trajectory <- vessel_trajectory %>%\n  filter(target == \"snappersnatcher7be\")\n```\n:::\n\n\nNext, the appropriate functions of `ggplot2` is used to plot the selected vessel \"Snapper Snatcher\" trajectories by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the data\nggplot() +\n  \n  # Plot the base map using oceanusgeography\n  geom_sf(data = oceanusgeography) +\n  \n   # Plot the trajectory as LINESTRING for the selected vessel\n  geom_sf(data = snapsnatch_trajectory, \n          aes(color = factor(target)), \n          size = 1) +\n  theme_minimal() +\n  \n  # Plot the individual points for the selected vessel\n  geom_sf(data = vessel_movement_sf %>% filter(target == \"snappersnatcher7be\"), \n          aes(color = factor(target)), \n          size = 2) +\n  \n  # Add labels to the individual points\n  geom_sf_text(data = vessel_movement_sf %>% filter(target == \"snappersnatcher7be\"), \n               aes(label = source, geometry = geometry), \n               size = 3, \n               color = \"black\") +\n  labs(title = \"Trajectories of Snapper Snatcher\", \n  x = \"Longitude\", y = \"Latitude\", color = \"ID\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nFrom the observations above, it is evident that Snapper Snatcher visited and dwelled at Ghoti Preserve, an ecological site not intended for fishing. This behavior is definitely suspicious.\n:::\n\nNow let's do the same for the second \"SouthSeafood Express Corp\" vessel, which is \"Roach Robber\" with the vessel ID `roachrobberdb6` and store the data in `roachrob_trajectory` data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroachrob_trajectory <- vessel_trajectory %>%\n  filter(target == \"roachrobberdb6\")\n```\n:::\n\n\nNext, the appropriate functions of `ggplot2` is used to plot the selected vessel \"Roach Robber\" trajectories by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the data\nggplot() +\n  \n  # Plot the base map using oceanusgeography\n  geom_sf(data = oceanusgeography) +\n  \n   # Plot the trajectory as LINESTRING for the selected vessel\n  geom_sf(data = roachrob_trajectory, \n          aes(color = factor(target)), \n          size = 1) +\n  theme_minimal() +\n  \n  # Plot the individual points for the selected vessel\n  geom_sf(data = vessel_movement_sf %>% filter(target == \"roachrobberdb6\"), \n          aes(color = factor(target)), \n          size = 2) +\n  \n  # Add labels to the individual points\n  geom_sf_text(data = vessel_movement_sf %>% filter(target == \"roachrobberdb6\"), \n               aes(label = source, geometry = geometry), \n               size = 3, \n               color = \"black\") +\n  labs(title = \"Trajectories of Roach Robber\", \n  x = \"Longitude\", y = \"Latitude\", color = \"ID\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Observation\"}\nFrom the observations above, it is appears that Roach Robber does not frequent any of the ecological preserve. No suspicious activity can be found.\n:::\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n## **Reference**\n\n-   Prof. Kam. [**Kickstarter2**](https://isss608-ay2023-24apr.netlify.app/vast/kickstarter2)\n\n-   Prof. Kam. [**Kickstarter3**](https://isss608-ay2023-24apr.netlify.app/vast/kickstarter3)\n",
    "supporting": [
      "Take-home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}